### ISSUE TITLE
2023/05/31あたりからコメントが取得できない

### ISSUE THREAD

**Issue by hoakari** [tsukumijima/jikkyo-api#10]
お疲れ様です。
2023/05/31あたりからコメントが取得できないようです。
ニコ生自体は動いていましたので取得プログラムが停止してるのでしょうか。
ご確認いただければと思います。よろしくお願いいたします。

**Comment by hoakari** [comment]
![image](https://github.com/tsukumijima/jikkyo-api/assets/46087819/06b734d3-e504-4e81-ac03-748eeb01ad19)
もしかしてこちらが原因でしょうか・・・

**Comment by tsukumijima** [comment]
はい、そういうことです。
3週間ほど前から GitHub からこの件について『サイズ減らすかしない限り消すよ』と通告を受けていたものの、5分おきにコミットするようになっていたためコミット数が膨大になっており、圧縮してもリポジトリサイズが数GB以上になることは確定的だったことから、ずっと対応せず後回しにしていた結果です…。
現在 Hugging Face への移行中ですが、相応の時間を要すると思われます。

**Comment by hoakari** [comment]
なるほどそういう事情だったのですね。
無償で保守していただいているので進めていただいてるだけでありがたいです。
私にとってなくてはならないものになっているのでご対応お待ちしております。

**Comment by tsukumijima** [comment]
取り急ぎ、Hugging Face (https://huggingface.co/datasets/KakologArchives/KakologArchives) に上がっている分の過去ログは再び取れるようになったのではないかと思います。
ただ過去ログを無圧縮で数百 GB 一気にアップロードしている関係で非常に時間がかかっており、完了まで丸一日かかりそうな雰囲気です。

**Comment by hoakari** [comment]
素晴らしいです！確認できました！！
ありがとうございます。

**Comment by tsukumijima** [comment]
<img width="768" alt="image" src="https://github.com/tsukumijima/jikkyo-api/assets/39271166/a0be80ab-cfbb-4664-be97-c483b07a2c41">

https://huggingface.co/datasets/KakologArchives/KakologArchives に完全移行しました。
手元の自宅サーバーで動かしている [JKCommentCrawler](https://github.com/tsukumijima/JKCommentCrawler) も更新し、5分おきに更新される状態になっているかと思います。
もし今後も何か問題があるようでしたら、またご報告いただけると助かります。
