### ISSUE TITLE
特定のチャンネル、日時を指定してコメント取得しようとすると、サーバーエラーが発生する

### ISSUE THREAD

**Issue by rchwhm** [tsukumijima/jikkyo-api#7]
下記のapi urlでコメントを取得することが出来ませんでした。
`https://jikkyo.tsukumijima.net/api/kakolog/jk1?starttime=1672482000&endtime=1672497905&format=json`

Webページのコンソールで、似たような条件で実行するとサーバーエラーが発生したと表示されました。

【指定条件】JK1: NHK総合 2022/12/31 19:20:00 ~ 2022/12/31 23:45:00
```
サーバーエラーが発生しました。過去ログ API に不具合がある可能性があります。(HTTP Error 500)
API URL: https://jikkyo.tsukumijima.net/api/kakolog/jk1?starttime=1672482000&endtime=1672497900&format=xml
```
こちらについてご確認いただくことは可能でしょうか。
よろしくお願いいたします。
（念の為12/31の他のチャンネルや、12/30の同チャンネルでも試してみたのですが、問題なくコメント取得できました。）

**Comment by tsukumijima** [comment]
ご報告いただきありがとうございます。こういうエラーはなかなか報告していただかないと発見できないので、とても助かります。

さて、今回のエラーですが、どうも JSON でのみ発生し、XML では同じ期間においても正常に取得できるようでした。
この過去ログ API では XML 的な形式で保存したデータをそのまま保存し、適宜 JSON に変換しているのですが、おそらく良くないデータが入っていて失敗していそうです。
特にこの今年の大晦日はニコ生自体が障害を起こしていたので、それが影響している可能性は大いにあります。

修正しておきますが、もし当該データが一刻も早くほしいとかであれば、一旦 XML で取得された方が良いかもしれません。そもそも JSON 形式はプログラムで利用する場合に XML よりもパースが楽ということで実装しているものですし…。

**Comment by tsukumijima** [comment]
結局、こちら側のサーバー構成の php.ini の memory_limit が足りなくなっていたのが原因でした。
256MB だとどうも JSON 化する際にメモリ不足になるようで、それでエラーになってしまっていました（上の URL の場合、JSON だけで 26MB もあるほど巨大な過去ログなので、やむを得ないか…）。

2048MB までメモリ最大使用量を広げたことで、問題なくダウンロードできるようになっているかと思います。
お試しいただけますと幸いです。ご報告ありがとうございました！とても助かりました。

**Comment by rchwhm** [comment]
早速なご対応ありがとうございます！
コメントをダウンロードすることができました。
とても助かりました🙇‍♀️
