### ISSUE TITLE
2023/04/05 12:35以降、一部コメントデータが抜けている

### ISSUE THREAD

**Issue by stormer-doggy** [tsukumijima/jikkyo-api#8]
お疲れ様です。
過去ログのデータを利用させていただいているのですが、
2023/04/05 12:35の後ぐらいから、コメントデータが入っていない箇所があるようです。
サーバーでコメント取得に失敗しているなどありませんでしょうか？
ご確認いただけますと幸いです。

**Comment by tsukumijima** [comment]
すみません…！！
てっきり過去ログ API 側の問題だと思っていたのですが、過去ログデータをひたすらアップロードしている https://github.com/KakologArchives/KakologArchives のリポジトリを見ると本当にデータが欠けてしまっていたようです…。

原因はバグではなく、JKCommentCrawler でのコメント収集に私が使っていたニコニコアカウントのプレミアム会員の有効期限が切れて一般会員に降格したことで、コメントが収集できなくなってしまったことでした。
なぜ少しだけコメントが収集できていたのかは謎ですが、いずれにせよ完全なものではなかったので、うまくいっていなかった数日分全てのコメントを再取得してあります。

現在は普通に取得できるのではないかと思います。大変ご迷惑をおかけしました…。

**Comment by stormer-doggy** [comment]
過去分のデータ再取得も出来たようで良かったです！
ご対応いただきありがとうございましたorz
